In [313]:
import os

In [314]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [315]:
df=pd.read_csv(r"C:\Users\mayur\OneDrive\Desktop\data science training\project\cutomer churn predition system\data\Telco-Customer-Churn.csv")

In [316]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [317]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [318]:
df.duplicated().sum()

np.int64(0)

In [319]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [320]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [321]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

encoding

In [322]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [323]:
df = df.drop('customerID', axis=1)

In [324]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [325]:
df['MultipleLines'].unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [326]:
df['Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [327]:
df.drop_duplicates()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [328]:
char = df.select_dtypes(include='object')
num = df.select_dtypes(exclude='object')

In [329]:
char

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
0,Female,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,No
1,Male,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,1889.5,No
2,Male,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,108.15,Yes
3,Male,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),1840.75,No
4,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,1990.5,No
7039,Female,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),7362.9,No
7040,Female,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,346.45,No
7041,Male,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,306.6,Yes
7042,Male,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),6844.5,No

In [330]:
char

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
0,Female,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,No
1,Male,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,1889.5,No
2,Male,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,108.15,Yes
3,Male,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),1840.75,No
4,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,1990.5,No
7039,Female,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),7362.9,No
7040,Female,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,346.45,No
7041,Male,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,306.6,Yes
7042,Male,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),6844.5,No

In [331]:
num

      SeniorCitizen  tenure  MonthlyCharges
0                 0       1           29.85
1                 0      34           56.95
2                 0       2           53.85
3                 0      45           42.30
4                 0       2           70.70
...             ...     ...             ...
7038              0      24           84.80
7039              0      72          103.20
7040              0      11           29.60
7041              1       4           74.40
7042              0      66          105.65

[7043 rows x 3 columns]

In [332]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['gender'] = le.fit_transform(df['gender'])

print(df)

      gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0          0              0     Yes         No       1           No
1          1              0      No         No      34          Yes
2          1              0      No         No       2          Yes
3          1              0      No         No      45           No
4          0              0      No         No       2          Yes
...      ...            ...     ...        ...     ...          ...
7038       1              0     Yes        Yes      24          Yes
7039       0              0     Yes        Yes      72          Yes
7040       0              0     Yes        Yes      11           No
7041       1              1     Yes         No       4          Yes
7042       1              0      No         No      66          Yes

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes
1                   No             DSL            Yes           No
2                   No             DSL            Yes          Yes
3     No phone service             DSL            Yes           No
4                   No     Fiber optic             No           No
...                ...             ...            ...          ...
7038               Yes             DSL            Yes           No
7039               Yes     Fiber optic             No          Yes
7040  No phone service             DSL            Yes           No
7041               Yes     Fiber optic             No           No
7042                No     Fiber optic            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]

In [333]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Partner'] = le.fit_transform(df['Partner'])

print(df)

      gender  SeniorCitizen  Partner Dependents  tenure PhoneService  \
0          0              0        1         No       1           No
1          1              0        0         No      34          Yes
2          1              0        0         No       2          Yes
3          1              0        0         No      45           No
4          0              0        0         No       2          Yes
...      ...            ...      ...        ...     ...          ...
7038       1              0        1        Yes      24          Yes
7039       0              0        1        Yes      72          Yes
7040       0              0        1        Yes      11           No
7041       1              1        1         No       4          Yes
7042       1              0        0         No      66          Yes

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes
1                   No             DSL            Yes           No
2                   No             DSL            Yes          Yes
3     No phone service             DSL            Yes           No
4                   No     Fiber optic             No           No
...                ...             ...            ...          ...
7038               Yes             DSL            Yes           No
7039               Yes     Fiber optic             No          Yes
7040  No phone service             DSL            Yes           No
7041               Yes     Fiber optic             No           No
7042                No     Fiber optic            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]

In [334]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Dependents'] = le.fit_transform(df['Dependents'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure PhoneService  \
0          0              0        1           0       1           No
1          1              0        0           0      34          Yes
2          1              0        0           0       2          Yes
3          1              0        0           0      45           No
4          0              0        0           0       2          Yes
...      ...            ...      ...         ...     ...          ...
7038       1              0        1           1      24          Yes
7039       0              0        1           1      72          Yes
7040       0              0        1           1      11           No
7041       1              1        1           0       4          Yes
7042       1              0        0           0      66          Yes

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes
1                   No             DSL            Yes           No
2                   No             DSL            Yes          Yes
3     No phone service             DSL            Yes           No
4                   No     Fiber optic             No           No
...                ...             ...            ...          ...
7038               Yes             DSL            Yes           No
7039               Yes     Fiber optic             No          Yes
7040  No phone service             DSL            Yes           No
7041               Yes     Fiber optic             No           No
7042                No     Fiber optic            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]

In [335]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['PhoneService'] = le.fit_transform(df['PhoneService'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes
1                   No             DSL            Yes           No
2                   No             DSL            Yes          Yes
3     No phone service             DSL            Yes           No
4                   No     Fiber optic             No           No
...                ...             ...            ...          ...
7038               Yes             DSL            Yes           No
7039               Yes     Fiber optic             No          Yes
7040  No phone service             DSL            Yes           No
7041               Yes     Fiber optic             No           No
7042                No     Fiber optic            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]

In [336]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['MultipleLines'] = le.fit_transform(df['MultipleLines'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0                 1             DSL             No          Yes
1                 0             DSL            Yes           No
2                 0             DSL            Yes          Yes
3                 1             DSL            Yes           No
4                 0     Fiber optic             No           No
...             ...             ...            ...          ...
7038              2             DSL            Yes           No
7039              2     Fiber optic             No          Yes
7040              1             DSL            Yes           No
7041              2     Fiber optic             No           No
7042              0     Fiber optic            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]

In [337]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['InternetService'] = le.fit_transform(df['InternetService'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService OnlineSecurity OnlineBackup  \
0                 1                0             No          Yes
1                 0                0            Yes           No
2                 0                0            Yes          Yes
3                 1                0            Yes           No
4                 0                1             No           No
...             ...              ...            ...          ...
7038              2                0            Yes           No
7039              2                1             No          Yes
7040              1                0            Yes           No
7041              2                1             No           No
7042              0                1            Yes           No

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0                 Yes           Electronic check           29.85        29.85
1                  No               Mailed check           56.95       1889.5
2                 Yes               Mailed check           53.85       108.15
3                  No  Bank transfer (automatic)           42.30      1840.75
4                 Yes           Electronic check           70.70       151.65
...               ...                        ...             ...          ...
7038              Yes               Mailed check           84.80       1990.5
7039              Yes    Credit card (automatic)          103.20       7362.9
7040              Yes           Electronic check           29.60       346.45
7041              Yes               Mailed check           74.40        306.6
7042              Yes  Bank transfer (automatic)          105.65       6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 20 columns]

In [338]:
df = pd.get_dummies(df, columns=['OnlineSecurity'])

In [339]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineBackup,DeviceProtection,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,OnlineSecurity_No,OnlineSecurity_No internet service,OnlineSecurity_Yes
0,0,0,1,0,1,0,1,0,Yes,No,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,True,False,False
1,1,0,0,0,34,1,0,0,No,Yes,...,No,One year,No,Mailed check,56.95,1889.5,No,False,False,True
2,1,0,0,0,2,1,0,0,Yes,No,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,False,False,True
3,1,0,0,0,45,0,1,0,No,Yes,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,False,False,True
4,0,0,0,0,2,1,0,1,No,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,No,Yes,...,Yes,One year,Yes,Mailed check,84.80,1990.5,No,False,False,True
7039,0,0,1,1,72,1,2,1,Yes,Yes,...,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,True,False,False
7040,0,0,1,1,11,0,1,0,No,No,...,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,False,False,True
7041,1,1,1,0,4,1,2,1,No,No,...,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,True,False,False
7042,1,0,0,0,66,1,0,1,No,Yes,...,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,False,False,True

In [340]:
print(df.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn', 'OnlineSecurity_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes']

In [341]:
print(df.select_dtypes(include='object').columns)

Index(['OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'TotalCharges', 'Churn'],
      dtype='object')

In [342]:
print(df["DeviceProtection"].unique())

['No' 'Yes' 'No internet service']

In [343]:
df = pd.get_dummies(df, columns=["DeviceProtection"], drop_first=True)

In [344]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [345]:
print(df["TotalCharges"].isnull().sum())

11

In [346]:
df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

C:\Users\mayur\AppData\Local\Temp\ipykernel_11320\1479199042.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

In [347]:
print(df.dtypes["TotalCharges"])

float64

In [348]:
print(df.select_dtypes(include="object").columns)

Index(['OnlineBackup', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='object')

In [349]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['TechSupport'] = le.fit_transform(df['TechSupport'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService OnlineBackup  TechSupport  ...  \
0                 1                0          Yes            0  ...
1                 0                0           No            0  ...
2                 0                0          Yes            0  ...
3                 1                0           No            2  ...
4                 0                1           No            0  ...
...             ...              ...          ...          ...  ...
7038              2                0           No            2  ...
7039              2                1          Yes            0  ...
7040              1                0           No            0  ...
7041              2                1           No            0  ...
7042              0                1           No            2  ...

     PaperlessBilling              PaymentMethod MonthlyCharges TotalCharges  \
0                 Yes           Electronic check          29.85        29.85
1                  No               Mailed check          56.95      1889.50
2                 Yes               Mailed check          53.85       108.15
3                  No  Bank transfer (automatic)          42.30      1840.75
4                 Yes           Electronic check          70.70       151.65
...               ...                        ...            ...          ...
7038              Yes               Mailed check          84.80      1990.50
7039              Yes    Credit card (automatic)         103.20      7362.90
7040              Yes           Electronic check          29.60       346.45
7041              Yes               Mailed check          74.40       306.60
7042              Yes  Bank transfer (automatic)         105.65      6844.50

     Churn  OnlineSecurity_No  OnlineSecurity_No internet service  \
0       No               True                               False
1       No              False                               False
2      Yes              False                               False
3       No              False                               False
4      Yes               True                               False
...    ...                ...                                 ...
7038    No              False                               False
7039    No               True                               False
7040    No              False                               False
7041   Yes               True                               False
7042    No              False                               False

     OnlineSecurity_Yes  DeviceProtection_No internet service  \
0                 False                                 False
1                  True                                 False
2                  True                                 False
3                  True                                 False
4                 False                                 False
...                 ...                                   ...
7038               True                                 False
7039              False                                 False
7040               True                                 False
7041              False                                 False
7042               True                                 False

      DeviceProtection_Yes
0                    False
1                     True
2                    False
3                     True
4                    False
...                    ...
7038                  True
7039                  True
7040                 False
7041                 False
7042                  True

[7043 rows x 23 columns]

In [350]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['StreamingTV'] = le.fit_transform(df['StreamingTV'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService OnlineBackup  TechSupport  ...  \
0                 1                0          Yes            0  ...
1                 0                0           No            0  ...
2                 0                0          Yes            0  ...
3                 1                0           No            2  ...
4                 0                1           No            0  ...
...             ...              ...          ...          ...  ...
7038              2                0           No            2  ...
7039              2                1          Yes            0  ...
7040              1                0           No            0  ...
7041              2                1           No            0  ...
7042              0                1           No            2  ...

      PaperlessBilling              PaymentMethod MonthlyCharges TotalCharges  \
0                  Yes           Electronic check          29.85        29.85
1                   No               Mailed check          56.95      1889.50
2                  Yes               Mailed check          53.85       108.15
3                   No  Bank transfer (automatic)          42.30      1840.75
4                  Yes           Electronic check          70.70       151.65
...                ...                        ...            ...          ...
7038               Yes               Mailed check          84.80      1990.50
7039               Yes    Credit card (automatic)         103.20      7362.90
7040               Yes           Electronic check          29.60       346.45
7041               Yes               Mailed check          74.40       306.60
7042               Yes  Bank transfer (automatic)         105.65      6844.50

     Churn  OnlineSecurity_No  OnlineSecurity_No internet service  \
0       No               True                               False
1       No              False                               False
2      Yes              False                               False
3       No              False                               False
4      Yes               True                               False
...    ...                ...                                 ...
7038    No              False                               False
7039    No               True                               False
7040    No              False                               False
7041   Yes               True                               False
7042    No              False                               False

     OnlineSecurity_Yes  DeviceProtection_No internet service  \
0                 False                                 False
1                  True                                 False
2                  True                                 False
3                  True                                 False
4                 False                                 False
...                 ...                                   ...
7038               True                                 False
7039              False                                 False
7040               True                                 False
7041              False                                 False
7042               True                                 False

      DeviceProtection_Yes
0                    False
1                     True
2                    False
3                     True
4                    False
...                    ...
7038                  True
7039                  True
7040                 False
7041                 False
7042                  True

[7043 rows x 23 columns]

In [351]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Contract'] = le.fit_transform(df['Contract'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService OnlineBackup  TechSupport  ...  \
0                 1                0          Yes            0  ...
1                 0                0           No            0  ...
2                 0                0          Yes            0  ...
3                 1                0           No            2  ...
4                 0                1           No            0  ...
...             ...              ...          ...          ...  ...
7038              2                0           No            2  ...
7039              2                1          Yes            0  ...
7040              1                0           No            0  ...
7041              2                1           No            0  ...
7042              0                1           No            2  ...

      PaperlessBilling              PaymentMethod  MonthlyCharges  \
0                  Yes           Electronic check           29.85
1                   No               Mailed check           56.95
2                  Yes               Mailed check           53.85
3                   No  Bank transfer (automatic)           42.30
4                  Yes           Electronic check           70.70
...                ...                        ...             ...
7038               Yes               Mailed check           84.80
7039               Yes    Credit card (automatic)          103.20
7040               Yes           Electronic check           29.60
7041               Yes               Mailed check           74.40
7042               Yes  Bank transfer (automatic)          105.65

     TotalCharges Churn  OnlineSecurity_No  \
0           29.85    No               True
1         1889.50    No              False
2          108.15   Yes              False
3         1840.75    No              False
4          151.65   Yes               True
...           ...   ...                ...
7038      1990.50    No              False
7039      7362.90    No               True
7040       346.45    No              False
7041       306.60   Yes               True
7042      6844.50    No              False

      OnlineSecurity_No internet service OnlineSecurity_Yes  \
0                                  False              False
1                                  False               True
2                                  False               True
3                                  False               True
4                                  False              False
...                                  ...                ...
7038                               False               True
7039                               False              False
7040                               False               True
7041                               False              False
7042                               False               True

      DeviceProtection_No internet service  DeviceProtection_Yes
0                                    False                 False
1                                    False                  True
2                                    False                 False
3                                    False                  True
4                                    False                 False
...                                    ...                   ...
7038                                 False                  True
7039                                 False                  True
7040                                 False                 False
7041                                 False                 False
7042                                 False                  True

[7043 rows x 23 columns]

In [352]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['PaperlessBilling'] = le.fit_transform(df['PaperlessBilling'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService OnlineBackup  TechSupport  ...  \
0                 1                0          Yes            0  ...
1                 0                0           No            0  ...
2                 0                0          Yes            0  ...
3                 1                0           No            2  ...
4                 0                1           No            0  ...
...             ...              ...          ...          ...  ...
7038              2                0           No            2  ...
7039              2                1          Yes            0  ...
7040              1                0           No            0  ...
7041              2                1           No            0  ...
7042              0                1           No            2  ...

      PaperlessBilling              PaymentMethod  MonthlyCharges  \
0                    1           Electronic check           29.85
1                    0               Mailed check           56.95
2                    1               Mailed check           53.85
3                    0  Bank transfer (automatic)           42.30
4                    1           Electronic check           70.70
...                ...                        ...             ...
7038                 1               Mailed check           84.80
7039                 1    Credit card (automatic)          103.20
7040                 1           Electronic check           29.60
7041                 1               Mailed check           74.40
7042                 1  Bank transfer (automatic)          105.65

      TotalCharges Churn  OnlineSecurity_No  \
0            29.85    No               True
1          1889.50    No              False
2           108.15   Yes              False
3          1840.75    No              False
4           151.65   Yes               True
...            ...   ...                ...
7038       1990.50    No              False
7039       7362.90    No               True
7040        346.45    No              False
7041        306.60   Yes               True
7042       6844.50    No              False

      OnlineSecurity_No internet service OnlineSecurity_Yes  \
0                                  False              False
1                                  False               True
2                                  False               True
3                                  False               True
4                                  False              False
...                                  ...                ...
7038                               False               True
7039                               False              False
7040                               False               True
7041                               False              False
7042                               False               True

      DeviceProtection_No internet service  DeviceProtection_Yes
0                                    False                 False
1                                    False                  True
2                                    False                 False
3                                    False                  True
4                                    False                 False
...                                    ...                   ...
7038                                 False                  True
7039                                 False                  True
7040                                 False                 False
7041                                 False                 False
7042                                 False                  True

[7043 rows x 23 columns]

In [353]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['PaymentMethod'] = le.fit_transform(df['PaymentMethod'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService OnlineBackup  TechSupport  ...  \
0                 1                0          Yes            0  ...
1                 0                0           No            0  ...
2                 0                0          Yes            0  ...
3                 1                0           No            2  ...
4                 0                1           No            0  ...
...             ...              ...          ...          ...  ...
7038              2                0           No            2  ...
7039              2                1          Yes            0  ...
7040              1                0           No            0  ...
7041              2                1           No            0  ...
7042              0                1           No            2  ...

      PaperlessBilling PaymentMethod  MonthlyCharges  TotalCharges  Churn  \
0                    1             2           29.85         29.85     No
1                    0             3           56.95       1889.50     No
2                    1             3           53.85        108.15    Yes
3                    0             0           42.30       1840.75     No
4                    1             2           70.70        151.65    Yes
...                ...           ...             ...           ...    ...
7038                 1             3           84.80       1990.50     No
7039                 1             1          103.20       7362.90     No
7040                 1             2           29.60        346.45     No
7041                 1             3           74.40        306.60    Yes
7042                 1             0          105.65       6844.50     No

      OnlineSecurity_No  OnlineSecurity_No internet service  \
0                  True                               False
1                 False                               False
2                 False                               False
3                 False                               False
4                  True                               False
...                 ...                                 ...
7038              False                               False
7039               True                               False
7040              False                               False
7041               True                               False
7042              False                               False

     OnlineSecurity_Yes  DeviceProtection_No internet service  \
0                 False                                 False
1                  True                                 False
2                  True                                 False
3                  True                                 False
4                 False                                 False
...                 ...                                   ...
7038               True                                 False
7039              False                                 False
7040               True                                 False
7041              False                                 False
7042               True                                 False

      DeviceProtection_Yes
0                    False
1                     True
2                    False
3                     True
4                    False
...                    ...
7038                  True
7039                  True
7040                 False
7041                 False
7042                  True

[7043 rows x 23 columns]

In [354]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['OnlineBackup'] = le.fit_transform(df['OnlineBackup'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService  OnlineBackup  TechSupport  ...  \
0                 1                0             2            0  ...
1                 0                0             0            0  ...
2                 0                0             2            0  ...
3                 1                0             0            2  ...
4                 0                1             0            0  ...
...             ...              ...           ...          ...  ...
7038              2                0             0            2  ...
7039              2                1             2            0  ...
7040              1                0             0            0  ...
7041              2                1             0            0  ...
7042              0                1             0            2  ...

      PaperlessBilling PaymentMethod  MonthlyCharges  TotalCharges  Churn  \
0                    1             2           29.85         29.85     No
1                    0             3           56.95       1889.50     No
2                    1             3           53.85        108.15    Yes
3                    0             0           42.30       1840.75     No
4                    1             2           70.70        151.65    Yes
...                ...           ...             ...           ...    ...
7038                 1             3           84.80       1990.50     No
7039                 1             1          103.20       7362.90     No
7040                 1             2           29.60        346.45     No
7041                 1             3           74.40        306.60    Yes
7042                 1             0          105.65       6844.50     No

      OnlineSecurity_No  OnlineSecurity_No internet service  \
0                  True                               False
1                 False                               False
2                 False                               False
3                 False                               False
4                  True                               False
...                 ...                                 ...
7038              False                               False
7039               True                               False
7040              False                               False
7041               True                               False
7042              False                               False

     OnlineSecurity_Yes  DeviceProtection_No internet service  \
0                 False                                 False
1                  True                                 False
2                  True                                 False
3                  True                                 False
4                 False                                 False
...                 ...                                   ...
7038               True                                 False
7039              False                                 False
7040               True                                 False
7041              False                                 False
7042               True                                 False

      DeviceProtection_Yes
0                    False
1                     True
2                    False
3                     True
4                    False
...                    ...
7038                  True
7039                  True
7040                 False
7041                 False
7042                  True

[7043 rows x 23 columns]

In [355]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineBackup,TechSupport,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,OnlineSecurity_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,DeviceProtection_No internet service,DeviceProtection_Yes
0,0,0,1,0,1,0,1,0,2,0,...,1,2,29.85,29.85,No,True,False,False,False,False
1,1,0,0,0,34,1,0,0,0,0,...,0,3,56.95,1889.50,No,False,False,True,False,True
2,1,0,0,0,2,1,0,0,2,0,...,1,3,53.85,108.15,Yes,False,False,True,False,False
3,1,0,0,0,45,0,1,0,0,2,...,0,0,42.30,1840.75,No,False,False,True,False,True
4,0,0,0,0,2,1,0,1,0,0,...,1,2,70.70,151.65,Yes,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,0,2,...,1,3,84.80,1990.50,No,False,False,True,False,True
7039,0,0,1,1,72,1,2,1,2,0,...,1,1,103.20,7362.90,No,True,False,False,False,True
7040,0,0,1,1,11,0,1,0,0,0,...,1,2,29.60,346.45,No,False,False,True,False,False
7041,1,1,1,0,4,1,2,1,0,0,...,1,3,74.40,306.60,Yes,True,False,False,False,False
7042,1,0,0,0,66,1,0,1,0,2,...,1,0,105.65,6844.50,No,False,False,True,False,True

In [356]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['StreamingMovies'] = le.fit_transform(df['StreamingMovies'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService  OnlineBackup  TechSupport  ...  \
0                 1                0             2            0  ...
1                 0                0             0            0  ...
2                 0                0             2            0  ...
3                 1                0             0            2  ...
4                 0                1             0            0  ...
...             ...              ...           ...          ...  ...
7038              2                0             0            2  ...
7039              2                1             2            0  ...
7040              1                0             0            0  ...
7041              2                1             0            0  ...
7042              0                1             0            2  ...

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  \
0                    1              2           29.85         29.85     No
1                    0              3           56.95       1889.50     No
2                    1              3           53.85        108.15    Yes
3                    0              0           42.30       1840.75     No
4                    1              2           70.70        151.65    Yes
...                ...            ...             ...           ...    ...
7038                 1              3           84.80       1990.50     No
7039                 1              1          103.20       7362.90     No
7040                 1              2           29.60        346.45     No
7041                 1              3           74.40        306.60    Yes
7042                 1              0          105.65       6844.50     No

      OnlineSecurity_No  OnlineSecurity_No internet service  \
0                  True                               False
1                 False                               False
2                 False                               False
3                 False                               False
4                  True                               False
...                 ...                                 ...
7038              False                               False
7039               True                               False
7040              False                               False
7041               True                               False
7042              False                               False

     OnlineSecurity_Yes  DeviceProtection_No internet service  \
0                 False                                 False
1                  True                                 False
2                  True                                 False
3                  True                                 False
4                 False                                 False
...                 ...                                   ...
7038               True                                 False
7039              False                                 False
7040               True                                 False
7041              False                                 False
7042               True                                 False

      DeviceProtection_Yes
0                    False
1                     True
2                    False
3                     True
4                    False
...                    ...
7038                  True
7039                  True
7040                 False
7041                 False
7042                  True

[7043 rows x 23 columns]

In [357]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Churn'] = le.fit_transform(df['Churn'])

print(df)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService  OnlineBackup  TechSupport  ...  \
0                 1                0             2            0  ...
1                 0                0             0            0  ...
2                 0                0             2            0  ...
3                 1                0             0            2  ...
4                 0                1             0            0  ...
...             ...              ...           ...          ...  ...
7038              2                0             0            2  ...
7039              2                1             2            0  ...
7040              1                0             0            0  ...
7041              2                1             0            0  ...
7042              0                1             0            2  ...

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  \
0                    1              2           29.85         29.85      0
1                    0              3           56.95       1889.50      0
2                    1              3           53.85        108.15      1
3                    0              0           42.30       1840.75      0
4                    1              2           70.70        151.65      1
...                ...            ...             ...           ...    ...
7038                 1              3           84.80       1990.50      0
7039                 1              1          103.20       7362.90      0
7040                 1              2           29.60        346.45      0
7041                 1              3           74.40        306.60      1
7042                 1              0          105.65       6844.50      0

      OnlineSecurity_No  OnlineSecurity_No internet service  \
0                  True                               False
1                 False                               False
2                 False                               False
3                 False                               False
4                  True                               False
...                 ...                                 ...
7038              False                               False
7039               True                               False
7040              False                               False
7041               True                               False
7042              False                               False

      OnlineSecurity_Yes  DeviceProtection_No internet service  \
0                  False                                 False
1                   True                                 False
2                   True                                 False
3                   True                                 False
4                  False                                 False
...                  ...                                   ...
7038                True                                 False
7039               False                                 False
7040                True                                 False
7041               False                                 False
7042                True                                 False

      DeviceProtection_Yes
0                    False
1                     True
2                    False
3                     True
4                    False
...                    ...
7038                  True
7039                  True
7040                 False
7041                 False
7042                  True

[7043 rows x 23 columns]

In [358]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineBackup,TechSupport,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,OnlineSecurity_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,DeviceProtection_No internet service,DeviceProtection_Yes
0,0,0,1,0,1,0,1,0,2,0,...,1,2,29.85,29.85,0,True,False,False,False,False
1,1,0,0,0,34,1,0,0,0,0,...,0,3,56.95,1889.50,0,False,False,True,False,True
2,1,0,0,0,2,1,0,0,2,0,...,1,3,53.85,108.15,1,False,False,True,False,False
3,1,0,0,0,45,0,1,0,0,2,...,0,0,42.30,1840.75,0,False,False,True,False,True
4,0,0,0,0,2,1,0,1,0,0,...,1,2,70.70,151.65,1,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,0,2,...,1,3,84.80,1990.50,0,False,False,True,False,True
7039,0,0,1,1,72,1,2,1,2,0,...,1,1,103.20,7362.90,0,True,False,False,False,True
7040,0,0,1,1,11,0,1,0,0,0,...,1,2,29.60,346.45,0,False,False,True,False,False
7041,1,1,1,0,4,1,2,1,0,0,...,1,3,74.40,306.60,1,True,False,False,False,False
7042,1,0,0,0,66,1,0,1,0,2,...,1,0,105.65,6844.50,0,False,False,True,False,True

In [359]:
bool_cols = df.select_dtypes(include='bool').columns

df[bool_cols] = df[bool_cols].astype(int)

In [360]:
df.to_csv("new.csv", index=False)

In [361]:
print(df.select_dtypes(include='object').columns)

Index([], dtype='object')

In [362]:
print(df.columns.tolist())

['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineBackup', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn', 'OnlineSecurity_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'DeviceProtection_No internet service', 'DeviceProtection_Yes']